package es.pedronanez.clubevenres.entities;

import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

/**
 * Object representing a diner's individual order.
 * @author Pedro
 *
 */
@Entity
@Table(name="diner")
public class Diner {

	/**
	 * Unique identifier. Autogenerated.
	 */
	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	private Integer id;	
	
	/**
	 * Name of the diner.
	 */
	@Column
	private String name;
	
	/**
	 * Selected plate for order.
	 */
    @PrimaryKeyJoinColumn
    @ManyToOne
	private Plate plate;
    
    /**
     * Removed ingredients for this order.
     */
	@ManyToMany
    @JoinTable(name="iorder_ingredients")
	private List<Ingredient> removedIngredients;
	
	/**
	 * Additional comments made by the diner.
	 */
	@Column
	private String comments;
	
	/**
	 * Indicates if diner wants french fries
	 */
	@Column
	private Boolean frenchFries;
	
	/**
	 * Sauce for french fries
	 */
	@PrimaryKeyJoinColumn
    @ManyToOne
	private Ingredient sauce;

	/**
	 * @return the id
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * @param id the id to set
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * @return the name
	 */
	public String getName() {
		return name;
	}

	/**
	 * @param name the name to set
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * @return the plate
	 */
	public Plate getPlate() {
		return plate;
	}

	/**
	 * @param plate the plate to set
	 */
	public void setPlate(Plate plate) {
		this.plate = plate;
	}

	/**
	 * @return the removedIngredients
	 */
	public List<Ingredient> getRemovedIngredients() {
		return removedIngredients;
	}

	/**
	 * @param removedIngredients the removedIngredients to set
	 */
	public void setRemovedIngredients(List<Ingredient> removedIngredients) {
		this.removedIngredients = removedIngredients;
	}

	/**
	 * @return the comments
	 */
	public String getComments() {
		return comments;
	}

	/**
	 * @param comments the comments to set
	 */
	public void setComments(String comments) {
		this.comments = comments;
	}

	/**
	 * @return the frenchFries
	 */
	public Boolean getFrenchFries() {
		return frenchFries;
	}

	/**
	 * @param frenchFries the frenchFries to set
	 */
	public void setFrenchFries(Boolean frenchFries) {
		this.frenchFries = frenchFries;
	}

	/**
	 * @return the sauce
	 */
	public Ingredient getSauce() {
		return sauce;
	}

	/**
	 * @param sauce the sauce to set
	 */
	public void setSauce(Ingredient sauce) {
		this.sauce = sauce;
	}
	
	
		
}
